Adding Radio Buttons
ESP-Number-One/MatchyoSports pull request #44
Opened 2024-02-20 16:03 UTC by ThomasCanning

Adding Radio Buttons. Create a group by setting the "name" parameter to the same thing. The radio buttons are referenced by their "value" and labeled with "label". The initailaly set button can also be changed. Set parameters is first and is last to add rounding to the corners of the first and last elements.

2024-02-21 17:19 UTC, WilfSilver commented
@ThomasCanning sammy told me this was a draft so have marked it as such. Do you agree with this decision/do you think its ready for a review?

2024-02-21 17:26 UTC, ThomasCanning commented
I think it's good to go, it's customised the same as in the figma pretty
much

On Wed, Feb 21, 2024, 17:19 WilfSilver ***@***.***> wrote:

> @ThomasCanning <https://github.com/ThomasCanning> sammy told me this was
> a draft so have marked it as such. Do you agree with this decision/do you
> think its ready for a review?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESP-Number-One/MatchyoSports/pull/44#issuecomment-1957372597>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQYZHAE55KPWIB7YYMLXYLYUYUDHAVCNFSM6AAAAABDRNUMSOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJXGM3TENJZG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-21 17:39 UTC, WilfSilver requested changes
I worry slightly about the implementation as its a bit more complicated to setup than I was expecting (as we have to wrap the buttons in a `div` with class `grid`)

2024-02-21 17:39 UTC, WilfSilver commented on packages/frontend/src/components/radio_button.tsx
> +// RadioButton.tsx
This can be removed

2024-02-21 17:39 UTC, WilfSilver commented on packages/frontend/src/components/radio_button.tsx
> +import React from "react";
`ReactNode` is not used, see [the failing check](https://github.com/ESP-Number-One/MatchyoSports/actions/runs/7976717417/job/21777924312#step:3:86). However it seems you use `React.ReactNode`, so you can instead remove the `React` import and remove replace `React.ReactNode` with `ReactNode` which I find more readable.

Note you will have to import `ChangeEvent`.

2024-02-21 17:39 UTC, WilfSilver commented on packages/frontend/src/components/radio_button.tsx
> +  checked = false,
I feel like this should be stored as a state inside the this object itself.

2024-02-23 17:48 UTC, WilfSilver commented
I have rebased your branch, on main.

Please run `git pull --force` before making any other changes

2024-03-09 10:31 UTC, WilfSilver commented
This was merged with #52

2024-03-09 10:31 UTC, closed without merging