Making profile picture work, you can click on it to open files and ch…
ESP-Number-One/MatchyoSports pull request #70
Opened 2024-03-01 16:09 UTC by ThomasCanning

…oose an image and click again to remove it

2024-03-01 16:10 UTC, ThomasCanning commented
I havent added tests yet but wanted to pull request componenent incase its needed

2024-03-02 09:17 UTC, WilfSilver requested changes
Wow this is amazing! Was not expecting this to be done, but looks great, just a few minor changes :)

This will also require tests written

2024-03-02 09:17 UTC, WilfSilver commented on packages/frontend/src/components/profile_picture.tsx
> +      style={{ width: "100%", paddingTop: "100%" }}
please use tailwindcss

2024-03-02 09:17 UTC, WilfSilver commented on packages/frontend/src/components/profile_picture.tsx
> +              accept="image/*"
We want to restrict this to the image formats we have tested on backed
```suggestion
              accept="image/png,image/jpeg,image/webp"
```

2024-03-02 09:17 UTC, WilfSilver commented on packages/frontend/src/components/profile_picture.tsx
> +  backgroundColor = "bg-p-grey-100",
We want to pass in an `onChange: (img: string) => void` function which passes in the image, so that we can have access to it in the page

2024-03-08 18:38 UTC, merged